In [1]:
import numpy as np
import torch

In [3]:
a = [0] * 2 + [1] * 3 + [2] * 4
a

[0, 0, 1, 1, 1, 2, 2, 2, 2]

In [21]:
c = [1,2,2,3,4,3,4,5,6]

In [16]:
b = [2,0,1,3]

In [17]:
a = np.array(a)

In [18]:
a.shape

(9,)

In [19]:
ind_a = np.where(b == a[:,None])

In [20]:
print(ind_a)
print(b)
print(a[:,None])

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]), array([1, 1, 2, 2, 2, 0, 0, 0, 0]))
[[0]
 [0]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]]


In [23]:
c = np.array(c)
c.shape

(9,)

In [25]:
ind_c = np.where(b == c[:,None])
print(ind_c)
print(b)
print(c[:,None])

(array([0, 1, 2, 3, 5]), array([2, 0, 0, 3, 3]))
[2, 0, 1, 3]
[[1]
 [2]
 [2]
 [3]
 [4]
 [3]
 [4]
 [5]
 [6]]
